### ISSUE TITLE
As a kev user, I have a way to create OR filters

### ISSUE THREAD

**Issue by bjinwright** [capless/kev#21]
I would like the interface to look like this.

`Posts.objects().or({"title":"How to write apps with Kev"}).or({"title":"Intro to Kev"})`

**Comment by armicron** [comment]
Is "don't use `scan()`" rule still eligible for this issue?
The aforementioned query can be made only with `scan()` method.

**Comment by bjinwright** [comment]
I think you can use the IN filter with Query.

**Comment by bjinwright** [comment]
Using ConditionExpressions http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html

**Comment by armicron** [comment]
>I think you can use the IN filter with Query.
>Using ConditionExpressions http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html

The documentation says:
>To manipulate data in a DynamoDB table, you use the **PutItem**, **UpdateItem** and **DeleteItem** operations. (You can also use **BatchWriteItem** to perform multiple PutItem or DeleteItem operations in a single call.)

>For these data manipulation operations, you can specify a condition expression to determine which items should be modified. If the condition expression evaluates to true, the operation succeeds; otherwise, the operation fails.

There is no information about `IN` filter with **Query** operation.

Boto3 documentation has a direct mention that `ConditionOperation` supports only `AND | OR` operations. Moreover, it's deprecated.
>ConditionalOperator (string) -- This is a legacy parameter. **Use FilterExpression instead**. For more information, see ConditionalOperator in the Amazon DynamoDB Developer.

[Boto3 DynamoDB documentation](http://boto3.readthedocs.io/en/latest/reference/services/dynamodb.html#DynamoDB.Client.query)

**Comment by bjinwright** [comment]
Ok use scan

**Comment by bjinwright** [comment]
Moved to DocB
