### ISSUE TITLE
As a developer, I can sort data returned from queries and all

### ISSUE THREAD

**Issue by bjinwright** [capless/kev#29]
```python

qs = Person.objects().filter({'age':34}).sort_by('age')
```

**Comment by armicron** [comment]
@bjinwright What to do if a backend doesn't support sorting (S3, S3Redis, Dynamo). Should KEV take responsibility of sorting or give a message that sorting is not supported?

**Comment by armicron** [comment]
`TestDocument.all()` method is not chainable right now, that means that result from this method can't be sorted with `all().sort_by(...)`. It needs to be moved to the `objects().all()`.

**Comment by bjinwright** [comment]
Ok I agree. Also, the sorting for the backends in kev should be handled kev.
