### ISSUE TITLE
Remove Python 2.7 Support?

### ISSUE THREAD

**Issue by bjinwright** [capless/kev#30]
Is there a real need for Python 2.7 support anymore? I initially supported because I run a lot of stuff on AWS Lambda but now that it supports 3.6 I am wondering if it is necessary. Am I jumping the gun on this one?

**Comment by bjinwright** [comment]
@armicron Thoughts?

**Comment by armicron** [comment]
@bjinwright I think it can be removed. 
>The End Of Life date (EOL, sunset date) for Python 2.7 has been moved five years into the future, to 2020.

**Comment by bjinwright** [comment]
Fixed in 4b96903d6fd2bc03a13e1151450c8ac0a0df8d1d
