### ISSUE TITLE
As a user, I can retrieve all documents in a consistent way on all backends.

### ISSUE THREAD

**Issue by bjinwright** [capless/kev#33]
There should be a consistent way to retrieve all documents and limit the number of documents returned for all backends.

```python 
#Returns the first 50 docs
TestDocument.all(limit=50)
#Returns all docs
TestDocument.all()
```

**Comment by armicron** [comment]
What about a Cloudant backend? It's still unmerged into develop branch.

**Comment by bjinwright** [comment]
I want to wait until we have a way to index docs

**Comment by bjinwright** [comment]
Actually I can merge it to develop just not master

**Comment by armicron** [comment]
Merging into develop will help.
