### ISSUE TITLE
Move DynamoDB and CloudantDB to capless/docb

### ISSUE THREAD

**Issue by bjinwright** [capless/kev#37]
I think splitting the key/value stores and document database backends is necessary for this project to move forward. The backends for S3, S3/Redis, and Redis will remain here. DynamoDB, Cloudant, and FaunaDB will move to [capless/docb](https://github.com/capless/docb).

**Comment by armicron** [comment]
@bjinwright should I keep commit's history for capeless/docb? If I will copy backends and commit them, then history will be lost.

**Comment by bjinwright** [comment]
Good idea.

**Comment by armicron** [comment]
So, I will clone kev into docb, then remove S3, S3/Reids, Redis backends, tests for them and change Readme right?

**Comment by bjinwright** [comment]
No, add a new *remote* in the .git/config of the kev repo locally.
```
[remote "docb"]
url = git@github.com:capless/docb.git
fetch = +refs/heads/*:refs/remotes/origin/*
```
Do a `git push docb`.

Then do a git clone of the docb repo

**Comment by armicron** [comment]
@bjinwright check permissions, please.
`remote: Permission to capless/docb.git denied to armicron.`

**Comment by bjinwright** [comment]
Ok you are good to go now
